"""add api_key to client model

Revision ID: 7466ab0e5e73
Revises: dbe5a65fd262
Create Date: 2025-11-02 16:19:44.937218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7466ab0e5e73'
down_revision = 'dbe5a65fd262'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('api_key', sa.String(length=64), nullable=True, comment='Уникальный API ключ для аутентификации'))
    op.create_index('ix_client_api_key', 'client', ['api_key'], unique=True)
    op.create_unique_constraint(None, 'client', ['api_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client', type_='unique')
    op.drop_index('ix_client_api_key', table_name='client')
    op.drop_column('client', 'api_key')
    # ### end Alembic commands ###