"""Initial database schema with all models

Revision ID: dbe5a65fd262
Revises: 
Create Date: 2025-11-01 12:22:53.005003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbe5a65fd262'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Название категории'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='ID родительской категории'),
    sa.Column('slug', sa.String(length=255), nullable=False, comment='Уникальный slug для URL'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index('uq_category_name_parent', 'categories', [sa.literal_column('lower(name)'), 'parent_id'], unique=True)
    op.create_table('client',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Имя клиента'),
    sa.Column('address', sa.Text(), nullable=True, comment='Адрес клиента'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_id'), 'client', ['id'], unique=False)
    op.create_table('nomenclature',
    sa.Column('sku', sa.String(length=100), nullable=False, comment='Артикул товара'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Название товара'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False, comment='Текущая цена'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='Остаток на складе'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index(op.f('ix_nomenclature_id'), 'nomenclature', ['id'], unique=False)
    op.create_table('nomenclature_categories',
    sa.Column('nomenclature_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['nomenclature_id'], ['nomenclature.id'], ),
    sa.PrimaryKeyConstraint('nomenclature_id', 'category_id')
    )
    op.create_table('order',
    sa.Column('client_id', sa.Integer(), nullable=False, comment='ID клиента'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Статус заказа: created/paid/shipped/completed/cancelled'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_id'), 'order', ['id'], unique=False)
    op.create_table('orderitem',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('nomenclature_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='Количество товара в заказе'),
    sa.Column('price_at_order', sa.Numeric(precision=10, scale=2), nullable=False, comment='Цена товара на момент заказа'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.CheckConstraint('quantity > 0', name='chk_order_item_quantity_positive'),
    sa.ForeignKeyConstraint(['nomenclature_id'], ['nomenclature.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orderitem_id'), 'orderitem', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orderitem_id'), table_name='orderitem')
    op.drop_table('orderitem')
    op.drop_index(op.f('ix_order_id'), table_name='order')
    op.drop_table('order')
    op.drop_table('nomenclature_categories')
    op.drop_index(op.f('ix_nomenclature_id'), table_name='nomenclature')
    op.drop_table('nomenclature')
    op.drop_index(op.f('ix_client_id'), table_name='client')
    op.drop_table('client')
    op.drop_index('uq_category_name_parent', table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###